### ISSUE TITLE
Packaging for Arch Linux

### ISSUE THREAD

**Issue by dvzrv** [panda-re/qcow-rs#1]
Hi! I've come across your qcow-cli tool and it appears to be very useful! Thanks for providing it!

I would like to package it for Arch Linux, however there are a few things that keep me from doing so:

- there are no tags for the CLI tool (e.g. `qcow-cli-0.3.1` or similar), that I can bind a build script to (I need a tag in a git repository or the accompanying auto-generated tarballs to build from)
- there is no Cargo.lock file for the CLI tool, which renders a resulting package not reproducible (see https://reproducible-builds.org/)

**Comment by jamcleod** [comment]
Hey! Sorry for the multi-month reply time, I've added the Cargo.lock in 9189780 and there is now a `qcow-cli-0.3.1` tag. For any future updates I will tag them in the `qcow-cli-X.Y.Z` format. I appreciate your interest and willingness to package for Arch, and apologies if this changes were too slow for your to be interested in still doing that! Thanks for the clear list on the changes you needed, let me know if you need anything else
